// Takes the final merged result and writes: 
//  <reportId>.json - machine readable, full structured data 
//  <reportId>.md - human-readable markdown with tables and code blocks.

import fs from "fs";
import path from "path";


const RISK_BADGE = {
  CRITICAL: " CRITICAL",
  HIGH: " HIGH",
  MEDIUM: " MEDIUM",
  LOW: " LOW",
  SAFE: " SAFE",
};

export async function generateReport({ report, outputDir, format, baseName }) {
  const written = [];

  if (format === "json" || format === "both") {
    const p = path.join(outputDir, `${baseName}.json`);
    fs.writeFileSync(p, JSON.stringify(report, null, 2), "utf-8");
    written.push(p);
  }

  if (format === "markdown" || format === "both") {
    const p = path.join(outputDir, `${baseName}.md`);
    fs.writeFileSync(p, buildMarkdown(report), "utf-8");
    written.push(p);
  }

  return written;
}

// Markdown builder

function buildMarkdown(report) {
  const {
    contractName, language, version, auditedAt, durationMs,
    auditScope, summary, overallRisk, findings,
    positives, gasOptimizations, auditNotes, storageId,
  } = report;

  // Severity counts
  const counts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0, INFORMATIONAL: 0 };
  findings.forEach((f) => { counts[f.severity] = (counts[f.severity] || 0) + 1; });

  const scopeLabel = {
    flagged: "Risky functions only (pass 1 triage)",
    all: "Full contract (all functions)",
    skip: "Pass 1 findings only (pass 2 skipped)",
  }[auditScope] || auditScope;

  let md = `# Agitt Smart Contract Audit Report
 
## Overview
 
| Field | Value |
|---|---|
| Contract | \`${contractName}\` |
| Language | ${language}${version ? ` \`${version}\`` : ""} |
| Audited At | ${auditedAt} |
| Duration | ${(durationMs / 1000).toFixed(2)}s |
| Audit Scope | ${scopeLabel} |
| Overall Risk | **${RISK_BADGE[overallRisk] || overallRisk}** |
${storageId ? `| 0G Storage ID | \`${storageId}\` |` : ""}
 
---
 
## Executive Summary
 
${summary || "_No summary provided._"}
 
---
 
## Finding Summary
 
| Severity | Count |
|---|---|
|  Critical | ${counts.CRITICAL} |
|  High | ${counts.HIGH} |
|  Medium | ${counts.MEDIUM} |
|  Low | ${counts.LOW} |
|  Informational | ${counts.INFORMATIONAL} |
| **Total** | **${findings.length}** |
 
---
 
## Findings
 
`;

  if (findings.length === 0) {
    md += "_No vulnerabilities found._\n\n";
  } else {
    for (const f of findings) {
      md += `### ${SEVERITY_EMOJI[f.severity] || ""} ${f.id} — ${f.title}
 
| Field | Detail |
|---|---|
| Severity | **${f.severity}** |
| Class | ${f.vulnerabilityClass} |
| Location | \`${f.location}\` |
| Pass | ${f.pass === 1 ? "Pass 1 (triage)" : "Pass 2 (deep audit)"} |
 
**Description**
 
${f.description}
 
`;
      if (f.codeSnippet) {
        md += `**Vulnerable Code**
 
\`\`\`${language}
${f.codeSnippet}
\`\`\`
 
`;
      }

      md += `**Remediation**
 
${f.remediation}
 
`;
      if (f.references?.length) {
        md += `**References**\n\n${f.references.map((r) => `- ${r}`).join("\n")}\n\n`;
      }

      md += "---\n\n";
    }
  }

  if (positives?.length) {
    md += `## Security Positives\n\n`;
    positives.forEach((p) => { md += `- ✅ ${p}\n`; });
    md += "\n---\n\n";
  }

  if (gasOptimizations?.length) {
    md += `## Gas Optimizations\n\n`;
    gasOptimizations.forEach((g) => { md += `- ⚡ ${g}\n`; });
    md += "\n---\n\n";
  }

  if (auditNotes) {
    md += `## Audit Notes\n\n${auditNotes}\n\n---\n\n`;
  }

  md += `_Report generated by [Agitt](https://github.com/yourorg/agitt)_\n`;
  return md;
}
